"""empty message

Revision ID: 016420135ee4
Revises: 
Create Date: 2021-12-16 15:11:00.358732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016420135ee4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('rol', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('imagen', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.String(length=120), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.String(length=120), nullable=True),
    sa.Column('valoracion', sa.String(length=120), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=True),
    sa.Column('facebook', sa.String(length=150), nullable=True),
    sa.Column('instagram', sa.String(length=150), nullable=True),
    sa.Column('nombre_empresa', sa.String(length=150), nullable=True),
    sa.Column('imagen', sa.String(length=120), nullable=True),
    sa.Column('agregar_evento', sa.String(length=120), nullable=True),
    sa.Column('editar_evento', sa.String(length=120), nullable=True),
    sa.Column('eliminar_evento', sa.String(length=120), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.rol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=200), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_favorito', sa.String(length=120), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_eventos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_eventos'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos_favoritos')
    op.drop_table('comentarios')
    op.drop_table('rol')
    op.drop_table('perfiles')
    op.drop_table('eventos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
